version: '3.7'

services:
  redis:
    image: redis:latest
    restart: always

  db1:
    environment:
      POSTGRES_USER: user1744
      POSTGRES_PASSWORD: pass1744
      POSTGRES_DB: sitedb
    image: postgres:latest
    restart: always

  wocker:
    build: .
    links: 
      - redis
      - db1
    restart: always
    environment: 
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - DATABASE_URL=postgresql://user1744:pass1744@db1/sitedb
    depends_on:
      - redis
      - db1
    entrypoint:  ["./celery.sh"]

  flask:
    build: .
    links: 
      - redis
      - db1
    ports:
      - "5500:5500"
    restart: always
    environment: 
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - DATABASE_URL=postgresql://user1744:pass1744@db1/sitedb
    depends_on:
      - redis
      - wocker
      - db1
    entrypoint: ["./boot.sh"]

