version: '3.7'

services:
  redis:
    image: redis:latest

  wocker:
    build: .
    links: 
      - redis
    ports:
      - "5501:5500"
    environment: 
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
    entrypoint:  ["./celery.sh"]

  flask:
    build: .
    links: 
      - redis
    ports:
      - "5500:5500"
    environment: 
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
      - wocker
    entrypoint: ["./boot.sh"]

